# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08my.proto\"?\n\x0fGoogleVisitorId\x12\x19\n\x11visitor_info_live\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x62\x06proto3'
)




_GOOGLEVISITORID = _descriptor.Descriptor(
  name='GoogleVisitorId',
  full_name='GoogleVisitorId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='visitor_info_live', full_name='GoogleVisitorId.visitor_info_live', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='GoogleVisitorId.timestamp', index=1,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['GoogleVisitorId'] = _GOOGLEVISITORID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GoogleVisitorId = _reflection.GeneratedProtocolMessageType('GoogleVisitorId', (_message.Message,), {
  'DESCRIPTOR' : _GOOGLEVISITORID,
  '__module__' : 'my_pb2'
  # @@protoc_insertion_point(class_scope:GoogleVisitorId)
  })
_sym_db.RegisterMessage(GoogleVisitorId)


# @@protoc_insertion_point(module_scope)
